"""
spring_gen.py
Generates a 3D-printable coil spring as a binary STL.

Parameters mirror the MakerWorld Parametric Model Maker:
  coils          – number of coils
  thickness      – wire cross-section height (mm)
  width          – wire cross-section width (mm)
  pitch          – axial distance per coil (mm)
  inside_dia     – inner diameter of the spring (mm)
  chamfer        – chamfer size on wire edges (mm)

The approach:
  1. Build a chamfered rectangular cross-section profile in 2-D.
  2. Sweep it along a helix path using Frenet-Serret frames.
  3. Cap both ends flat.
  4. Write binary STL.
"""

import math
import struct
import numpy as np


# ---------------------------------------------------------------------------
# Cross-section profile (chamfered rectangle, in local XY)
# ---------------------------------------------------------------------------

def chamfered_rect_profile(w, h, chamfer):
    """
    Returns an (N, 2) array of vertices for a chamfered rectangle.
    Centred at origin, width=w (X), height=h (Y).
    chamfer is clipped to half the shorter side.
    """
    c = min(chamfer, w / 2 - 0.01, h / 2 - 0.01)
    hw, hh = w / 2, h / 2
    pts = np.array([
        [-hw + c,  -hh     ],
        [ hw - c,  -hh     ],
        [ hw,      -hh + c ],
        [ hw,       hh - c ],
        [ hw - c,   hh     ],
        [-hw + c,   hh     ],
        [-hw,       hh - c ],
        [-hw,      -hh + c ],
    ])
    return pts


# ---------------------------------------------------------------------------
# Helix path + Frenet frames
# ---------------------------------------------------------------------------

def helix_frames(coils, pitch, radius, n_per_coil=64):
    """
    Returns positions (N,3) and rotation matrices (N,3,3) along the helix.
    radius = inside_dia/2 + width/2  (centreline radius)

    Uses the analytical Frenet-Serret frame for a helix:
      T = (-R*sin(t), R*cos(t), h) / sqrt(R²+h²)
      N = (-cos(t), -sin(t), 0)          (radially inward)
      B = T × N
    where h = pitch / (2π).
    """
    N = int(coils * n_per_coil)
    t = np.linspace(0, coils * 2 * math.pi, N, endpoint=True)

    h = pitch / (2 * math.pi)
    denom = math.sqrt(radius ** 2 + h ** 2)

    x = radius * np.cos(t)
    y = radius * np.sin(t)
    z = h * t
    pos = np.stack([x, y, z], axis=1)  # (N,3)

    # Tangent (analytical)
    tang = np.stack(
        [-radius * np.sin(t), radius * np.cos(t), np.full(N, h)], axis=1
    ) / denom

    # Principal normal: always points radially inward for a helix
    norm = np.stack([-np.cos(t), -np.sin(t), np.zeros(N)], axis=1)

    # Binormal: T × N (unit length since T and N are orthonormal)
    binorm = np.cross(tang, norm)

    # Rotation matrix: columns = [norm, binorm, tang]  (local X, Y, Z -> world)
    R = np.stack([norm, binorm, tang], axis=2)  # (N,3,3)

    return pos, R


# ---------------------------------------------------------------------------
# Sweep & mesh
# ---------------------------------------------------------------------------

def sweep_profile(profile_2d, positions, rotations):
    """
    Maps each 2-D profile point through each Frenet frame.
    Returns (N_frames, N_pts, 3) world-space positions.
    """
    N = len(positions)
    P = len(profile_2d)
    # Extend profile to 3-D: (x, y, 0)
    prof3 = np.zeros((P, 3))
    prof3[:, :2] = profile_2d

    rings = np.zeros((N, P, 3))
    for i in range(N):
        # rotations[i] : (3,3) where col0=norm, col1=binorm, col2=tang
        # We want to place the profile in the (norm, binorm) plane
        rings[i] = positions[i] + (rotations[i] @ prof3.T).T

    return rings


def rings_to_triangles(rings):
    """
    Builds triangles for the lateral (tube) surface from ring array (N,P,3).
    Returns list of (3,3) triangles.
    """
    N, P, _ = rings.shape
    tris = []
    for i in range(N - 1):
        for j in range(P):
            j1 = (j + 1) % P
            a = rings[i,  j ]
            b = rings[i,  j1]
            c = rings[i+1,j ]
            d = rings[i+1,j1]
            tris.append((a, b, d))
            tris.append((a, d, c))
    return tris


def fan_triangles(centre, ring):
    """Triangulate a flat end cap from a centre point + ring."""
    P = len(ring)
    tris = []
    for j in range(P):
        j1 = (j + 1) % P
        tris.append((centre, ring[j], ring[j1]))
    return tris


# ---------------------------------------------------------------------------
# STL writer
# ---------------------------------------------------------------------------

def triangle_normal(t):
    a, b, c = t
    n = np.cross(b - a, c - a)
    l = np.linalg.norm(n)
    return n / l if l > 1e-12 else n


def write_binary_stl(triangles, path):
    header_text = b"Spring STL generated by spring_gen.py"
    header = header_text + b" " * (80 - len(header_text))
    count = len(triangles)
    with open(path, "wb") as f:
        f.write(header)
        f.write(struct.pack("<I", count))
        for tri in triangles:
            n = triangle_normal(tri)
            f.write(struct.pack("<fff", *n))
            for v in tri:
                f.write(struct.pack("<fff", *v))
            f.write(struct.pack("<H", 0))


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def generate_spring_stl(
    coils=15,
    thickness=1.7,
    width=2.0,
    pitch=4.0,
    inside_dia=6.0,
    chamfer=0.5,
    n_per_coil=80,
    output_path="spring.stl",
):
    """
    Generate a spring STL and write it to output_path.
    Returns output_path on success.
    """
    radius = inside_dia / 2 + width / 2

    profile = chamfered_rect_profile(width, thickness, chamfer)
    positions, rotations = helix_frames(coils, pitch, radius, n_per_coil)
    rings = sweep_profile(profile, positions, rotations)

    triangles = rings_to_triangles(rings)

    # End caps
    cap0_centre = positions[0]
    cap1_centre = positions[-1]
    # Flip winding on first cap so normals point outward
    cap0_ring = rings[0]
    cap1_ring = rings[-1]

    for tri in fan_triangles(cap0_centre, cap0_ring[::-1]):
        triangles.append(tri)
    for tri in fan_triangles(cap1_centre, cap1_ring):
        triangles.append(tri)

    write_binary_stl(
        [np.array(t, dtype=np.float32) for t in triangles],
        output_path,
    )
    return output_path


# ---------------------------------------------------------------------------
# Quick test
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    out = generate_spring_stl(output_path="/tmp/test_spring.stl")
    print(f"Written: {out}")
    import os
    print(f"Size: {os.path.getsize(out):,} bytes")
